[package]
name = "AOC2020"
version = "0.1.0"
authors = ["Trivaxy <itsmeomar2003@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
